### ISSUE TITLE
Maze is reset when arduino serial monitor is started or cable conected

### ISSUE THREAD

**Issue by derekchall** [ukmars/ukmarsbot-mazerunner#4]
When the serial monitor is connected, it sends a reset and the current program clears the maze so if you are using that you can’t look at the maze after a run. It is also not posable to use the chips registers to work out if a power on reset has occurred as the boot loader resets the flags before handing over control to the program. I added the flowing code to mazerunner.ino to reset the maze only if the button is pressed on reset/power up or if the content of mazemap[0](the start cell) is invalid
```
if (button_pressed() or !((walls[0] == 0xE) or (walls[0] == 0xFE))) { //reset maze if start is not correct or button pressed on reset
    initialise_maze(emptyMaze);
    Serial.println(F("Maze reset"));
  }
```

**Comment by micromouseonline** [comment]
A previous version had provision for this but for some reason, I took it out of the release.

For readers who have not looked at the code - the maze data is retained througfh a soft reset because it is stored in unittialised memory. Power-on reset will fill RAM with random values. 

Generally I find it easiest to assume the maze data is good following a reset and always clear the maze after a power-up. Your method is simpler though I worry a little about the maze wall data being correct in the first cell when testing new code.

The bootloader is especially annoying in obscuring the cause of the last reset so normally I do it old-school style with a magic value in RAM.

In mazerunner.ino:
```
static unsigned long boot_magic __attribute__((section(".noinit")));
```

in setup():
```
  if (boot_magic == 0xDECAFBAD) {  
    Serial.println(F("\nExternal Reset.\n"));
  } else {                          
    Serial.println(F("\nPower Up - clearing maze.\n"));
    initialise_maze(emptyMaze);
    boot_magic = 0xDECAFBAD;
  }
```
